### PR TITLE
datasource-formula: added antlr runtime version to Manifest

### PR DESCRIPTION
**Pull request by berryma4**
https://github.com/diirt/diirt/issues/64

### CODE REVIEW

**Comment by kasemir** [comment]
This change creates a downstream error in the SNS build of `cs-studio/core`:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building diirt-repository 4.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

...

[INFO] --- tycho-p2-repository-plugin:0.23.1:assemble-repository (default-assemble-repository) @ diirt-repository ---
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: diirt-repository raw:4.2.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.2.0-SNAPSHOT
[ERROR]   Missing requirement: org.diirt.datasource-formula 3.0.1.20160105060709 requires 'package org.antlr.runtime 3.4.0' but it could not be found
[ERROR]   Cannot satisfy dependency: diirt-repository raw:4.2.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.2.0-SNAPSHOT depends on: org.csstudio.core.diirt.feature.feature.group [0.0.1,0.0.2)
[ERROR]   Cannot satisfy dependency: org.csstudio.core.diirt.feature.feature.group 0.0.1.201601051119 depends on: org.diirt.datasource-formula [3.0.1.20160105060709]
```

Maybe the core.diirt.feature now needs to somehow include a plugin that provides the org.antlr.runtime package? With `Import-Package` instead of `Require-Bundle`, finding the actual plugin is left as an exercise ..

**Comment by shroffk** [comment]
I can confirm that I am seeing the same error.

I also tried adding the antlr plugin(org.antlr.runtime_3.4.0 bundle) to the diirt feature but that did not succeed either.

**Comment by kasemir** [comment]
Greetings from maven. When I rebuild all once more, the error is still related to `org.diirt.datasource-formula ..  requires .. package org.antlr.runtime`, but this time already in the dependency resolution phase:

```
[INFO] Resolving dependencies of MavenProject: org.csstudio:org.csstudio.utility.pvmanager.ui.toolbox:3.2.0-SNAPSHOT @ /usr/local/hudson/config/jobs/CSS_3_cs-studio/workspace/core/utility/utility-plugins/org.csstudio.utility.pvmanager.ui.toolbox/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.csstudio.utility.pvmanager.ui.toolbox 3.2.0.qualifier
[ERROR]   Missing requirement: org.diirt.datasource-formula 3.0.1.20160105084430 requires 'package org.antlr.runtime 3.4.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.csstudio.utility.pvmanager.ui.toolbox 3.2.0.qualifier depends on: package org.diirt.datasource.formula 3.0.0
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.csstudio:org.csstudio.utility.pvmanager.ui.toolbox:3.2.0-SNAPSHOT @ /usr/local/hudson/config/jobs/CSS_3_cs-studio/workspace/core/utility/utility-plugins/org.csstudio.utility.pvmanager.ui.toolbox/pom.xml: See log for details -> [Help 1]
```

**Comment by berryma4** [comment]
Does this have to do with 3.4 vs 3.4.0?

**Comment by shroffk** [comment]
I am not sure I understand, are you referring to the antlr runtime version number property in the pom.xml in diirt?

If that was the issues, wouldn't the dependency error appear when build the diirt/p2 instead of the cs-studio/core/diirt

**Comment by berryma4** [comment]
I'm back in the office and looking into it.

**Comment by shroffk** [comment]
Ok, So I tried the latest pull request submitted by @berryma4 with the version numbers defined as a range and the previous build issue is resolved.

**Comment by kasemir** [comment]
cs-studio/core again builds for me as well.
Thanks!!

**Pull request merged**
