### PR TITLE
javafx/tools: Remove web pods datasource

### PR DESCRIPTION
**Pull request by shroffk**
Refer to the initila discussion here: #21 

I have made a pull on the master with the dependency updated.
@willrogers @kasemir 

In the future I will look at having the pods modules added back so that the whole of diirt can be build without dependency issues like this.

Note:
Delete branch after merge

### CODE REVIEW

**Comment by shroffk** [comment]
@willrogers should we make a new release too?

**Comment by willrogers** [comment]
I'm not sure why we could build 3.1.1 when this problem was there.  Now it's built I _think_ we can still depend on it ok.

However, I think it's tidier just to make a new release 3.1.2.

**Comment by shroffk** [comment]
Here is what I think was happening, it could be that there was a locally built snapshot version of the pods module available in the local maven repo which was being resolved.

**Comment by willrogers** [comment]
Yes, that was my guess too...

**Pull request merged**
